server:
  port: 8080
spring:
  application:
    name: bfit-management-system
  profiles:
    active: dev
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace